name:               MPC-HC
description:        MPC-HC, the free, open source media player for Windows
lang:               en

markdown:           kramdown
highlighter:        false

plugins:
  - jekyll-avatar
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  # we generate those files ourselves
  - "*.css"
  - "*.js"

# https://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "news"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  -
    scope:
      path: ""
    values:
      image:
        path: "/assets/img/logo-256x256.png"
        height: 256
        width: 256

# paginate
paginate:           10
paginate_path:      archive/page:num

# permalinks
permalink:          pretty

# server
source:             source
destination:        _site
port:               8000
url:                https://mpc-hc.org
encoding:           UTF-8

# custom variables
version:
  short:            1.7.13
  long:             1.7.13.0
  hash:             "e37826845"
  date:             "16 July 2017"

feed:
  description:      Latest information about the MPC-HC project.
  path:             rss.xml
  url:              https://mpc-hc.org

news_limit:         5

# jekyll-seo-tag
logo:               "/assets/img/logo-256x256.png"

facebook:
  app_id:           1552669435051497

twitter:
  username:         mpc_hc

social:
  name:             MPC-HC
  links:
    - "https://www.facebook.com/MediaPlayerClassicHomeCinema"
    - "https://twitter.com/mpc_hc/"
    - "https://plus.google.com/+Mpc-hcOrg/"
